include(CheckCXXCompilerFlag)
include(CheckCCompilerFlag)

function(add_flag_if_supported)
    set(options)
    set(oneValueArgs LANGUAGE)
    set(multiValueArgs TARGETS FLAGS)
    cmake_parse_arguments(ARG "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    foreach (FLAG IN LISTS ARG_FLAGS)
        if (NOT ARG_LANGUAGE OR ARG_LANGUAGE STREQUAL "CXX")
            check_cxx_compiler_flag("${FLAG}" HAS_FLAG)
        elseif (ARG_LANGUAGE STREQUAL "C")
            check_c_compiler_flag("${FLAG}" HAS_FLAG)
        else ()
            message(AUTHOR_WARNING "LANGUAGE argument to add_flag_if_supported must be either CXX (default) or C")
        endif ()

        if (HAS_FLAG)
            foreach (TGT IN LISTS ARG_TARGETS)
                target_compile_options("${TGT}" PRIVATE "${FLAG}")
            endforeach ()
        endif ()
    endforeach ()
endfunction()